### ISSUE TITLE
デプロイしたReactからRais APIを叩くとcorsエラーになる。

### ISSUE THREAD

**Issue by HidetosHibino** [HidetosHibino/cocoaer-backend#14]
デプロイしたReactアプリからRails APIを呼ぶと、corsエラーで弾かれています。
(React: S3 + cloudFront, https://web.cocoaer.net 
 Rails API :  Fragment, https://api.cocoaer.net )
以下の教材を参考に実装。
https://zenn.dev/prune/books/28c2d690e11e45/viewer/e87aa4

Railsのcors.rbでは　"https://web.cocoaer.net" を許可しているのに、corsエラーとなっています。

<img width="852" alt="image" src="https://github.com/HidetosHibino/cocoaer-backend/assets/109229123/62d908b1-0db5-48d4-9eb4-e3175f2502a3">

corsエラーを出しているので、APIサーバは立ち上がって動いてはいると判断しています。

検索すると以下のような記事ですが、cors.rbは対応しているので別の問題なのかと思っています。
https://zenn.dev/mochiblock/articles/75db325ee7ea67

開発環境では同様の事象を見たことなく、何が原因でしょうか？どう原因を突き止めたら良いでしょうか？

**Comment by Tsuchiya2** [comment]
情報が少ないため分かりかねますが。。（上記参考教材も見れない状態でした）

表示されているエラー内容がなぜ出ているのか調べたりしましょう。
...has been blocked by CORS policy: .... だったり、net::ERR_FAILED 503 だったり、サーバー側のログだったりを見たり、調べたりして何が原因なのか仮説立てを行って、検証＆試行錯誤してみてください。
